SistemInformasi/routes/web.php
<?php

use App\Http\Controllers\Dashboard;
use App\Http\Controllers\Home;
use App\Http\Controllers\DosenController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MataKuliahController;
use App\Http\Controllers\RiwayatController;


Route::get('/', Home::class)->name('home');
Route::get('/dashboard', Dashboard::class)->name('dashboard')->middleware('auth');

Route::resources([
    'dosen' => DosenController::class,
    'mahasiswa' => MahasiswaController::class,
    'matakuliah' => MataKuliahController::class,
    'riwayat' => \App\Http\Controllers\RiwayatController::class,
    'kelas' => \App\Http\Controllers\KelasController::class,
    'dosenmatakuliah' => \App\Http\Controllers\DosenMataKuliahController::class,
]);

Route::get('/dosen/createriwayat/{id}', [DosenController::class, 'createriwayat']);
Route::post('/dosen/storeriwayat', [DosenController::class, 'storeriwayat']);

Route::get('/matakuliah/createkelas/{id}', [MataKuliahController::class, 'createkelas']);
Route::post('/matakuliah/storekelas', [MataKuliahController::class, 'storekelas']);

Route::get('/dosen/matakuliah/tambah/{matakuliah_id}/{dosen_id}',[DosenController::class, 'tambahmatakuliahdosen']);
Route::get('/dosen/matakuliah/hapus/{matakuliah_id}/{dosen_id}',[DosenController::class, 'hapusmatakuliahdosen']);

Route::get('/mahasiswa/kelas/tambah/{kelas_id}/{mahasiswa_id}',[MahasiswaController::class, 'tambahkelasmahasiswa']);
Route::get('/mahasiswa/kelas/hapus/{kelas_id}/{mahasiswa_id}',[MahasiswaController::class, 'hapuskelasmahasiswa']);

SistemInformasi/app/Models/Dosen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravolt\Suitable\AutoSearch;
use Laravolt\Suitable\AutoSort;

class Dosen extends Model
{
    use AutoSearch,AutoSort;
    use HasFactory;
    protected $table = 'dosen';
    protected $searchableColumns = ['nama','nip','gelar'];
    protected $fillable = ['nama','nip','gelar'];

    public function riwayat_pendidikan()
    {
        return $this->hasMany('App\Models\Riwayat');
    }

    public function matakuliah()
    {
        return $this->belongsToMany('App\Models\MataKuliah');
    }
}

SistemInformasi/app/Http/Controllers/DosenController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DosenStoreRequest;
use App\Http\Requests\DosenUpdateRequest;
use App\Http\Requests\RiwayatStoreRequest;
use App\Models\Riwayat;
use Illuminate\Http\Request;
use App\Models\Dosen;
use Illuminate\Support\Facades\DB;

class DosenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dosen = Dosen::autoSearch(\request('search'))->autoSort()->paginate(5);

        return view('dosen.index', compact('dosen'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dosen.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DosenStoreRequest $request)
    {
        Dosen::create($request->except('_token'));

        return redirect()->route('dosen.index')->withSuccess('Berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Dosen $dosen)
    {
        $sudah = DB::select('select * from matakuliah where id = any (select matakuliah_id from dosen_matakuliah where dosen_id = :id)', ['id' => $dosen->id]);
        foreach ($sudah as $s)
        {
            $s->dosen_id = $dosen->id;
        }
        $belum = DB::select('select * from matakuliah where id not in (select matakuliah_id from dosen_matakuliah where dosen_id = :id)', ['id' => $dosen->id]);
        foreach ($belum as $b)
        {
            $b->dosen_id = $dosen->id;
        }
        return view('dosen.riwayat', compact('dosen','sudah','belum'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Dosen $dosen)
    {
        return view('dosen.edit', compact('dosen'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DosenUpdateRequest $request,Dosen $dosen)
    {
        $dosen->update($request->except('_token'));
        return redirect()->route('dosen.index')->withSuccess('Berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dosen $dosen)
    {
        $riwayat = Riwayat::where('dosen_id',$dosen->id)->get();
        $jumlahriwayat = count($riwayat);
        if ($jumlahriwayat > 0)
        {
            return redirect()->back()->withErrors('Dosen masih memiliki riwayat');
        }
        $matakuliah = DB::table('dosen_matakuliah')->where('dosen_id', $dosen->id)->get();
        $jumlahmatakuliah = count($matakuliah);
        if ($jumlahmatakuliah > 0)
        {
            return redirect()->back()->withErrors('Dosen Masih memiliki Mata Kuliah');
        }
        $dosen->delete();

        return redirect()->back()->withSuccess('Berhasil dihapus');
    }

    public function createriwayat($id)
    {
        return view('dosen.createriwayat',compact('id'));
    }

    public function storeriwayat(RiwayatStoreRequest $request)
    {
        Riwayat::create($request->except('_token'));

        return redirect()->route('dosen.show', $request->dosen_id)->withSuccess('Berhasil disimpan');
    }

    public function tambahmatakuliahdosen($matakuliah_id,$dosen_id)
    {
        DB::table('dosen_matakuliah')->insert([
            'matakuliah_id' => $matakuliah_id,
            'dosen_id' => $dosen_id
        ]);

        return redirect()->route('dosen.show', $dosen_id)->withSuccess('Berhasil ditambah');
    }

    public function hapusmatakuliahdosen($matakuliah_id,$dosen_id)
    {
        DB::table('dosen_matakuliah')->where([
            ['matakuliah_id', $matakuliah_id],
            ['dosen_id', $dosen_id],
        ])->delete();

        return redirect()->route('dosen.show', $dosen_id)->withSuccess('Berhasil dihapus');
    }
}

SistemInformasi/resources/views/dosen/_form.blade.php
{!! form()->text('nama')->label('Nama') !!}
{!! form()->text('nip')->label('NIP') !!}
{!! form()->text('gelar')->label('Gelar') !!}
{!! form()->link('<i class="ui icon angle left"></i> Batal', route('dosen.index')) !!}
{!! form()->submit('Simpan') !!}

SistemInformasi/resources/views/dosen/_formriwayat.blade.php
{!! form()->text('strata')->label('Strata') !!}
{!! form()->text('jurusan')->label('Jurusan') !!}
{!! form()->text('sekolah')->label('Sekolah') !!}
{!! form()->text('tahun_mulai')->label('Tahun mulai') !!}
{!! form()->text('tahun_selesai')->label('Tahun selesai') !!}
{!! form()->submit('Simpan') !!}

SistemInformasi/resources/views/dosen/create.blade.php
@extends('laravolt::layouts.app')

@section('content')
    <x-titlebar title="Tambah Dosen" />

    {!! form()->open(route('dosen.store')) !!}
    @include('dosen._form')
    {!! form()->close() !!}

@stop

SistemInformasi/resources/views/dosen/createriwayat.blade.php
@extends('laravolt::layouts.app')

@section('content')
    <x-titlebar title="Tambah Riwayat" />

    {!! form()->open('/dosen/storeriwayat') !!}
    {!! form()->hidden('dosen_id', $id) !!}
    @include('dosen._formriwayat')
    {!! form()->close() !!}

@stop

SistemInformasi/resources/views/dosen/edit.blade.php
@extends('laravolt::layouts.app')

@section('content')
    <x-titlebar title="Edit Dosen" />

    {!! form()->bind($dosen)->put(route('dosen.update', $dosen->id)) !!}
    @include('dosen._form')
    {!! form()->close() !!}

@stop

SistemInformasi/resources/views/dosen/editriwayat.blade.php
@extends('laravolt::layouts.app')

@section('content')
    <x-titlebar title="Edit Riwayat" />

    {!! form()->bind($riwayat)->put(route('riwayat.update', $riwayat->id)) !!}
    @include('dosen._formriwayat')
    {!! form()->close() !!}

@stop

SistemInformasi/resources/views/dosen/index.blade.php
@extends('laravolt::layouts.app')

@section('content')
    <x-titlebar title="Dosen">
        <x-item>
            <x-link label="tambah" icon="plus" url="{{ route('dosen.create') }}"></x-link>
        </x-item>
    </x-titlebar>

    {!! Suitable::source($dosen)->search()->columns([
            Laravolt\Suitable\Columns\Numbering::make('No'),
            Laravolt\Suitable\Columns\Text::make('nama','nama')->sortable('nama'),
            Laravolt\Suitable\Columns\Text::make('nip','nip')->sortable(),
            Laravolt\Suitable\Columns\Text::make('gelar','gelar')->sortable(),
            Laravolt\Suitable\Columns\RestfulButton::make('dosen', 'Action'),
        ])->render()
    !!}

@stop

SistemInformasi/resources/views/dosen/riwayat.blade.php
@extends('laravolt::layouts.app')

@section('content')
    <x-titlebar title="Detail Dosen"/>
    <div class="ui grid">
        <div class="row">
            <div class="two wide column">
                <strong>Nama</strong>
            </div>
            <div class="two wide column">{{$dosen->nama}}</div>
        </div>
        <div class="row">
            <div class="two wide column">
                <strong>NIP</strong>
            </div>
            <div class="two wide column">{{$dosen->nip}}</div>
        </div>
        <div class="row">
            <div class="two wide column">
                <strong>Gelar</strong>
            </div>
            <div class="two wide column">{{$dosen->gelar}}</div>
        </div>

    </div>
    <br>

    <h3 class="ui header">Riwayat Pendidikan Dosen</h3>
    <x-link label="tambah" icon="plus" url="{{ 'createriwayat/'.$dosen->id}}"></x-link>
    {!! Suitable::source($dosen->riwayat_pendidikan)->search()->columns([
            Laravolt\Suitable\Columns\Numbering::make('No'),
            Laravolt\Suitable\Columns\Text::make('strata','strata')->sortable(),
            Laravolt\Suitable\Columns\Text::make('jurusan','jurusan')->sortable(),
            Laravolt\Suitable\Columns\Text::make('sekolah','sekolah')->sortable(),
            Laravolt\Suitable\Columns\Text::make('tahun_mulai','tahun_mulai')->sortable(),
            Laravolt\Suitable\Columns\Text::make('tahun_selesai','tahun_selesai')->sortable(),
            Laravolt\Suitable\Columns\RestfulButton::make('riwayat', 'Action')->except('view'),
        ])->render()
    !!}

    <br>

    <h3 class="ui header">Mata Kuliah yang diambil</h3>
    {!! Suitable::source($sudah)->search()->columns([
            Laravolt\Suitable\Columns\Numbering::make('No'),
            Laravolt\Suitable\Columns\Text::make('nama','nama')->sortable(),
            Laravolt\Suitable\Columns\Text::make('sks','sks')->sortable(),
            ['header' => 'Action', 'raw' => function($rows){
                $val = '<a href="/dosen/matakuliah/hapus/'.$rows->id.'/'.$rows->dosen_id.'" class="ui button red mini icon secondary" data-tooltip="Hapus" data-position="top center">
                 <i aria-hidden="true" class="icon trash"></i></a>';
                return $val;
            }],
        ])->render()
    !!}

    <br>
    <h3 class="ui header">Mata Kuliah yang Tersedia</h3>
    {!! Suitable::source($belum)->search()->columns([
            Laravolt\Suitable\Columns\Numbering::make('No'),
            Laravolt\Suitable\Columns\Text::make('nama','nama')->sortable(),
            Laravolt\Suitable\Columns\Text::make('sks','sks')->sortable(),
            ['header' => 'Action', 'raw' => function($rows){
                $val = '<a href="/dosen/matakuliah/tambah/'.$rows->id.'/'.$rows->dosen_id.'" class="ui button green mini icon secondary" data-tooltip="Tambah" data-position="top center">
                 <i aria-hidden="true" class="icon plus"></i></a>';
                return $val;
            }],
        ])->render()
    !!}
@endsection